# Change these first
owner: MatteoGheza # Your GitHub organization or username, where this repository lives
repo: status.matteogheza.it # The name of this repository

sites:
  - name: VVFVolontariDarfo
    url: https://www.vvfvolontaridarfo.it
  - name: VPS Status
    check: "tcp-ping"
    url: $VPS_IP
    port: 80
  - name: Sagrest
    url: https://sagrest.it

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.matteogheza.it
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MatteoGheza uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "This page shows if some of the websites that I'm following are online."
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
